CREATE TABLE IF NOT EXISTS "ReorderCallAbort" (
  "id" SERIAL PRIMARY KEY,
  "leadId" INTEGER NOT NULL,
  "userId" INTEGER NOT NULL,
  "abortedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ReorderCallAbort_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "ReorderLead"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
