CREATE TABLE IF NOT EXISTS "CprBatch" (
  "id" SERIAL PRIMARY KEY,
  "appliedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fileCount" INTEGER NOT NULL DEFAULT 1,
  "payments" INTEGER NOT NULL,
  "returned" INTEGER NOT NULL,
  "notFound" INTEGER NOT NULL,
  "totalSettled" DOUBLE PRECISION NOT NULL
);
