ALTER TABLE "ReorderLead" DROP COLUMN IF EXISTS "pendingAttemptAt";
ALTER TABLE "ReorderCallLog" ADD COLUMN IF NOT EXISTS "openCount" INTEGER NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS "ReorderCallAttempt" (
  "id" SERIAL PRIMARY KEY,
  "leadId" INTEGER NOT NULL,
  "userId" INTEGER NOT NULL,
  "openedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ReorderCallAttempt_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "ReorderLead"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
